@startuml
'https://plantuml.com/class-diagram

hide circle
hide methods

class Account{
Full name
Address
Private mobile
Work mobile
Birthday
Zipcode
City
}

class Hobby{
Name
Category
Type
Link to wikipedia
}

Account "1 " .. "1..*" Hobby
@enduml